export * from "./ElectricPage";
export * from "./FirePage";
export * from "./GroundPage";
export * from "./HomePage";
export * from "./IcePage";
export * from "./PoisonPage";
export * from "./PokemonPage";
export * from "./WaterPage";
export * from "./SearchPage";
